spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: carry-porter
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:carry_porter}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
